parameters:
#    pass_base_site.example.class: PassBase\SiteBundle\Example

services:
#    pass_base_site.example:
#        class: %pass_base_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
