parameters:
#    pass_base_integration.example.class: PassBase\IntegrationBundle\Example

services:
#    pass_base_integration.example:
#        class: %pass_base_integration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
